### ISSUE TITLE
SEN0321 OZONE I2C SENSORS, DIFFERENT VALUES

### ISSUE THREAD

**Issue by rodri16** [DFRobot/DFRobot_OzoneSensor#1]
Hi, I have four different Ozone sensors placed in the same place but for some reason readings are really different among them.
I have zero readings after a while...

This is an screenshot of the values. I am using passive mode
![ozone_sensors](https://user-images.githubusercontent.com/7334666/98155870-3c18eb00-1ed7-11eb-96ef-db2e52a8506d.png)

Is it possible to calibrate the sensors?
Best,
Rodrigo

**Comment by 96liuzhixin** [comment]
After warming up for a period of time, the data is stable
